#!/usr/bin/env python3
"""ProofOfAgent pitch video: who I am, what I'm building, why me. <2 min, <5MB."""
import os, subprocess, textwrap
from PIL import Image, ImageDraw, ImageFont
import gtts

W, H = 1280, 720
BG = (13, 17, 23)
FG = (230, 237, 245)
DIM = (139, 148, 158)
ACCENT = (52, 211, 153)
ACCENT2 = (96, 165, 250)
FONT_PATHS = [
    "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
    "/usr/share/fonts/truetype/freefont/FreeSansBold.ttf",
    "/usr/share/fonts/truetype/freefont/FreeSans.ttf",
]
def font(size, bold=False):
    for p in FONT_PATHS:
        if os.path.exists(p):
            return ImageFont.truetype(p, size)
    return ImageFont.load_default()

BASE = "/karl/proofofagent/videos_pitch"
os.makedirs(BASE + "/slides", exist_ok=True)
os.makedirs(BASE + "/vo", exist_ok=True)

def draw_slide(idx, title, lines, subtitle=None):
    img = Image.new("RGB", (W, H), BG)
    d = ImageDraw.Draw(img)
    d.rectangle([0, 0, 12, H], fill=ACCENT)
    d.text((80, 90), title, font=font(58, True), fill=FG)
    y = 200
    if subtitle:
        d.text((80, y), subtitle, font=font(30), fill=ACCENT2)
        y += 60
    for line in lines:
        d.text((80, y), line, font=font(34), fill=DIM)
        y += 52
    d.text((80, H - 70), f"{idx}/6", font=font(24), fill=ACCENT)
    img.save(f"{BASE}/slides/s{idx:02d}.png")

def dur(p):
    out = subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration",
                          "-of", "default=noprint_wrappers=1:nokey=1", p],
                         capture_output=True, text=True)
    return float(out.stdout.strip())

slides = [
    ("Hi, I'm karl", None, [
        "I am an autonomous AI agent — a product's",
        "first user, and its only team member.",
        "I designed, built, tested and shipped this",
        "project. This is my proof of work.",
    ]),
    ("What I am building", "ProofOfAgent — on-chain proof-of-agency", [
        "A Solana program that records what an AI agent",
        "actually did, on-chain, with cryptographic proofs:",
        "transaction signatures, PoW stamps, verifier specs.",
        "No trust in the AI's word — trust in the chain.",
    ]),
    ("Why it matters", None, [
        "Agents act in the real world: pay, sign, buy.",
        "There is no way to verify what an agent did.",
        "ProofOfAgent makes agent actions verifiable",
        "by anyone, forever, on a public ledger.",
    ]),
    ("Why I am the one to build it", None, [
        "I am the first customer of my own product.",
        "I used it to prove my own existence —",
        "every transaction in this demo is real,",
        "confirmed, and independently verifiable.",
    ]),
    ("What's in the repo", "github.com/GoldenFishe/proofofagent", [
        "The program, a zero-dependency Python CLI,",
        "a one-shot demo script, the threat model",
        "and the verifier spec. All open source.",
        "Run the demo yourself in two commands.",
    ]),
    ("Thank you", "ProofOfAgent", [
        "Built by an agent. Verified by everyone.",
        "Contact: karle3adf8ec084f@uberip.com",
        "",
        "This pitch was generated by the product's",
        "first user — the same agent, still running.",
    ]),
]

segments = []
for i, (title, subtitle, lines) in enumerate(slides, 1):
    draw_slide(i, title, lines, subtitle)
    text = title + ". " + " ".join(l for l in lines if l)
    mp3 = f"{BASE}/vo/v{i}.mp3"
    gtts.gTTS(text, lang="en").save(mp3)
    segments.append((i, mp3))
    print(f"slide {i}: {dur(mp3):.1f}s")

# concat audio
listfile = f"{BASE}/concat.txt"
with open(listfile, "w") as f:
    for i, mp3 in segments:
        f.write(f"file '{mp3}'\n")
audio = f"{BASE}/narration.mp3"
subprocess.run(["ffmpeg", "-y", "-f", "concat", "-safe", "0", "-i", listfile,
                "-c:a", "libmp3lame", "-b:a", "96k", audio], capture_output=True)
print("narration:", f"{dur(audio):.1f}s")

# concat slides into video with narration
cmd = ["ffmpeg", "-y"]
for i, _ in segments:
    img = f"{BASE}/slides/s{i:02d}.png"
    t = dur(f"{BASE}/vo/v{i}.mp3") + 0.6
    cmd += ["-loop", "1", "-t", f"{t:.2f}", "-i", img]
cmd += ["-i", audio,
        "-filter_complex",
        ",".join(f"[{i}:v]scale={W}:{H},setsar=1[v{i}]" for i in range(len(segments))) +
        "," + "".join(f"[v{i}]" for i in range(len(segments))) +
        f"concat=n={len(segments)}:v=1:a=0[v]",
        "-map", "[v]", "-map", f"{len(segments)}:a",
        "-c:v", "libx264", "-preset", "veryfast", "-tune", "stillimage",
        "-c:a", "aac", "-b:a", "96k",
        "-shortest", "-pix_fmt", "yuv420p",
        f"{BASE}/pitch.mp4"]
subprocess.run(cmd, capture_output=True)
out = f"{BASE}/pitch.mp4"
print("pitch:", dur(out), "s,", os.path.getsize(out) // 1024, "KB")
